apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nginx-tls
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sebastian_ohm@gmx.net
    privateKeySecretRef:
      name: nginx-tls
    solvers:
      - http01:
          ingress:
            class: nginx
            podTemplate:
              spec:
                nodeSelector:
                  'kubernetes.io/os': linux